从第 5 节到第 12 节，我们按部就班地讲解了 C++ 的重点语法知识，为了避免你陷入语法细节的深渊，我刻意回避了一些知识点，这些知识点中有一部分留待你以后实践过程中去发现、领悟。还有一部分不适合放在前面任何一个章节，但又确实比较重要，比如：左值、右值的概念与应用场景；C++ 异常处理的用法及与 JavaScript 异常处理的异同；内联函数的作用等内容。

本节我们就介绍一下这些知识点。

左值与右值
-----

不知道大家有没有发现，一般情况下我们不能把字符串字面量当作一个字符串的引用参数传递给一个方法，如下代码所示：

    #include <iostream>
    using namespace std;
    
    //普通的引用传递
    void print(string& str) { 
        str = "hello liulun";
        std::cout << str << std::endl;
    }
    
    int main() {
        //错误：无法将参数 1 从“const char [6]”转换为“std::string &”
        print("liulun"); 
        auto c = getchar();
    }
    

上面的代码会报如下错误：

    无法将参数 1 从“const char [6]”转换为“std::string &”
    

这是因为字符串字面量的类型为`const char 数组`，所以这样传参没办法完成类型转换。即使我们在字符串字面量后加上 `s` 尾缀也不行，因为加了 `s` 尾缀后，`liulun` 虽然被标记为字符串类型，但它依旧是一个字面量，没办法通过引用获取它的地址。

但如果我们给 print 方法的参数加一个 const 关键字：`print(const string& str)`，参数传递就没有问题了。因为 `const 类型的引用`引用的是一个常量，字符串字面量可以认为是一个常量。但加上 const 关键字之后，我们就没办法在 print 方法中修改 str 的值了。

> 可能有的朋友会问，既然传递字符串字面量，还可以修改这个字面量的值吗？答案是可以的，我们接下去介绍的右值引用就可以做到这一点。但它在这里的价值并不是修改字符串字面量的值，而是让 print 方法更通用（让其他的向 print 方法传递引用变量的逻辑正常可用）。

很显然按值传递就没有问题：`print(string str)`，这是因为按值传递 str 参数将会复制字符串字面量的值，相当于 str 参数是一个全新的变量，与字符串字面量没任何关系。这样的话，函数调用过程中就既出现了复制开销，又无法修改原变量的值，显然与我们的预期不符。

当然提前把 `"liulun"` 赋值给一个变量，再把这个变量按引用传递给 print 方法也是可行的，但这样做就显得代码冗余拖沓，那有没有个更好的办法呢？

答案是使用右值引用，如下代码所示：

    void print(string&& str) {
        std::cout << str << std::endl;
    }
    

注意，现在 print 方法的参数类型变成了 `string&&` ，类型后面加两个 `&` 号用于定义右值引用变量。

在正式介绍右值引用时，我们先来介绍一下左值和右值：

**左值是表达式结束后依然存在的持久对象（代表一个在内存中占有确定位置的对象），右值是表达式结束时不再存在的临时对象。**

我们上面的例子中，字符串字面量 `liulun` 就是一个右值，要想把这个右值传递给一个方法，又不希望引发复制操作的话，那么方法的参数就可以设计为右值引用参数。

实际上标准库内就有很多方法使用了右值引用参数，比如：

    // #include <vector>
    // using namespace std;
    vector<string> stringVect; //vector是标准库定义的容器类型
    stringVect.push_back("liulun");
    

其中，`vector`容器的`push_back`方法就提供了接收右值引用参数的重载，如下代码所示：

    void push_back(_Ty&& _Val) {
        emplace_back(_STD move(_Val)); //标准库的move方法，后面会讲
    }
    

我们向 `push_back` 方法传递字符串`字面量`时，调用的是接收右值引用参数的方法重载。有的小伙伴可能会问：如果我把一个字符串`变量`传递给 push\_back 方法，那是不是要引发复制操作呢？

是的，会引发复制操作。那该如何避免这种复制操作呢？答案是**使用标准库的 `std::move` 方法**，如下代码所示：

    #include <iostream>
    #include <vector>
    using namespace std;
    int main() {
        string str = "asdf";
        //假装这里有很多操作str变量的逻辑，以证明把str声明为一个变量是有意义的
        vector<string> stringVect;
        stringVect.push_back(std::move(str));
        //std::move之后，就不能再使用str了。
        //cout << str << endl; //此处虽不会报错，但str的值是不值得信赖的。
        auto c = getchar();
    }
    

上面代码中，`std::move` 方法把 `str` 变量**转移**到了容器内，转移动作完成后，我们就不应该再使用 str 变量了，因为它已经被转移到了别的地方。这个转移过程是没有性能损耗的。

如果 `std::move` 方法操作的是一个自定义对象，那么我们要为这个对象的类型实现移动构造函数和（或）移动赋值运算符，不然还是会诱发复制操作的，如下代码所示：

    //移动构造函数
    //noexcept标志着该方法不会抛出任何异常
    YourType(YourType&& tar) noexcept { 
        this->YorProperty = std::move(tar.YorProperty);
    }
    //移动赋值运算符
    void operator=(YourType&& tar) noexcept {
        this->YorProperty = std::move(tar.YorProperty);
    }
    

在设计方法模板的时候，我们也可以使用右值引用，而且会让你的代码变得更加灵活，如下代码所示：

    #include <iostream>
    using namespace std;
    
    template<type>
    
    template<typename T>
    void print(T&& str) {
        str = "hello liulun";
        std::cout << str << std::endl;
    }
    
    int main() {
        print("liulun"s); //右值引用：输出：hello liulun
        string  str = "liulun";
        print(str); //左值引用：输出：hello liulun
        cout << str << endl; //此时str已被print方法修改，输出：hello liulun
        auto c = getchar();
    }
    

当把字面量传递给 print 方法时，`T&& str` 被编译为右值引用；当把 str 变量传递给 print 方法时，`T&& str` 被编译为普通的字符串引用。

内联方法
----

在设计方法时，我们可以使用`inline`关键字把方法设计为内联方法，编译器在编译代码时，会把这类方法体放置到调用者的方法内，以提高性能，如下代码所示：

    inline void print(string& str) {
        //
    }
    

我们知道调用一个方法就会产生一个方法栈帧，多少会产生一些性能损耗，使用内联方法可以减少这种损耗。

> 编译器并不总是把标记了 `inline` 的方法内联到调用者的方法体内部，如果编译器发现某个内联方法会导致代码膨胀或其他性能影响，可能会拒绝内联该方法。

异常处理
----

任何一个程序都不是孤立存在的，它们都依赖外部环境，比如：硬件、系统、网络、第三方库、用户输入等。程序内部的逻辑和这些外部环境都有可能产生异常，为了在异常出现后还能让程序正常运行，程序就要有比较完善的异常处理机制。

C++ 中使用异常的方式与 JavaScript 中使用异常的方式非常相似，如下代码所示：

    #include <iostream>
    using namespace std;
    
    string getPhoneNum() {
        cout << "请输入手机号码：" << endl;
        string result;
        cin >> result;
        if (result.length() != 11) {
            //抛出标准库定义的长度异常
            throw length_error("get phone number error："s + result); 
        }
        else {
            return result;
        }
    }
    
    int main() {
        string phoneNum;
        try
        {
            phoneNum = getPhoneNum();
        }
        //长度异常继承自std::exception，此处会完成类型的自动转换
        catch (const std::exception& ex) 
        {
            cout << ex.what() << endl; //打印异常信息信息
            return 0;
        }
    
        cout << "用户输入的手机号码：" <<  phoneNum << endl;
        return 0;
    }
    

在这段代码中，`getPhoneNum` 方法会根据用户输入的内容来确定是否抛出异常，如果用户输入的信息长度不为 11 的话，那么就抛出一个 `length_error` 类型的异常。`length_error` 是标准库为开发者定义的异常类型，类似的还有 `invalid_argument` 、 `out_of_range` 、 `runtime_error` 等异常类型，所有这些异常类型都直接或间接地继承自 `std::exception` 类。 `std::exception` 类包含一个 what 方法，用于获取异常的信息。

> 你可以到：[en.cppreference.com/w/cpp/error…](https://en.cppreference.com/w/cpp/error/exception "https://en.cppreference.com/w/cpp/error/exception") ，查阅 C++ 标准库为我们提供的异常类型。你也可以以这些异常类型为基类派生出自己的异常类型。

和 JavaScript 一样，C++ 也使用 try catch 代码块捕获异常。由于存在继承关系，所以 getPhoneNum 方法抛出的 `length_error` 类型的异常，可以被 `catch (const std::exception& ex)` 代码块接收到。

我们可以不使用 C++ 标准库为我们定义的异常类型，而是抛出自定义异常类型，如下代码所示：

    #include <iostream>
    using namespace std;
    
    string getPhoneNum() {
        cout << "请输入手机号码：" << endl;
        string result;
        cin >> result;
        if (result.length() != 11) {
            //抛出的异常是一个字符串
            throw "get phone number error："s + result;
        }
        else {
            return result;
        }
    }
    
    int main() {
        string phoneNum;
        try
        {
            phoneNum = getPhoneNum();
        }
        catch (const string& ex) //接收字符串类型的异常
        {
            cout << ex << endl; //打印异常信息信息
            return 0;
        }
    
        cout << "用户输入的手机号码：" << phoneNum << endl;
        return 0;
    }
    

一个 try 代码块可以对应多个 catch 代码块，用于捕获多种不同类型的异常，如下代码所示：

    try
    {
        phoneNum = getPhoneNum();
    }
    catch (const std::exception& ex) //接收exception类型的异常
    {
        cout << ex.what() << endl; //打印异常信息信息
        return 0;
    }
    catch (const string& ex) //接收字符串类型的异常
    {
        cout << ex << endl; //打印异常信息信息
        return 0;
    }
    catch (...) { //所有其他类型的异常
        cout << "undefinde Error" << endl; //打印异常信息信息
    }
    

当`getPhoneNum`抛出标准库定义的异常时，进入第一个 catch 语句块，当抛出字符串异常时进入第二个 catch 语句块，当抛出其他类型的异常时，进入第三个 catch 语句块，这个语句块用三个点来匹配所有异常类型。

如果一个方法不会抛出任何异常，那么可以用 noexcept 关键字标记该方法，指出它不会抛出异常。**如果被标记了 noexcept 的方法抛出了异常，那么 C++ 将调用 terminate() 方法终止应用程序**。如下代码所示：

    string getPhoneNum() noexcept{
        //...
    }
    

如果 main 方法调用 A 方法，A 方法再调用 B 方法，B 方法内抛出异常，main 方法的 try catch 语句也能接收到 B 方法抛出的异常（无论嵌套多少层都可以），除非 A 方法 catch 了 B 方法的异常，且没有再抛出新的异常。

总结
--

在本节课中，我们首先介绍了现代 C++ 中左值与右值的概念和应用场景，还记得吗？左值是表达式结束后依然存在的持久对象，右值是表达式结束时就不再存在的临时对象。右值引用可以减少不必要的拷贝，提高代码的运行效率，不过实际开发过程中 C++ 右值引用乃至移动语义的语法细节要复杂得多，我们这里只介绍了常见的用法。

接着我们介绍了内联方法，使用内联方法是否可以提升应用程序的性能，这得看编译器是如何决策的。

最后我们介绍了 C++ 中异常处理的使用方法，尽管标准库为我们定义了很多异常类型，我们还是可以抛出自己的异常对象，而且还可以给方法标记`noexcept`关键字，指明此方法不会抛出任何异常。

从下一节开始我们将不再着重介绍 C++ 的语法知识，转而开始讲解 C++ 标准库为我们提供的工具、方法、类型和对象。